//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Persistence.Components.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PersistenceDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PersistenceDialog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Persistence.Components.Localization.PersistenceDialog", typeof(PersistenceDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster.
        /// </summary>
        internal static string Cluster {
            get {
                return ResourceManager.GetString("Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster file.
        /// </summary>
        internal static string ClusterFile {
            get {
                return ResourceManager.GetString("ClusterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateVerb {
            get {
                return ResourceManager.GetString("CreateVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import replaces the current cluster..
        /// </summary>
        internal static string ImportExportHint {
            get {
                return ResourceManager.GetString("ImportExportHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string LoadVerb {
            get {
                return ResourceManager.GetString("LoadVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new empty cluster..
        /// </summary>
        internal static string NewClusterHint {
            get {
                return ResourceManager.GetString("NewClusterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty.
        /// </summary>
        internal static string SaveSlotEmpty {
            get {
                return ResourceManager.GetString("SaveSlotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} KB.
        /// </summary>
        internal static string SaveSlotSize {
            get {
                return ResourceManager.GetString("SaveSlotSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot {0}.
        /// </summary>
        internal static string SaveSlotWithNumber {
            get {
                return ResourceManager.GetString("SaveSlotWithNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start up.
        /// </summary>
        internal static string StartUp {
            get {
                return ResourceManager.GetString("StartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded on start-up..
        /// </summary>
        internal static string StartUpSlotHint {
            get {
                return ResourceManager.GetString("StartUpSlotHint", resourceCulture);
            }
        }
    }
}
