<Project>
  <PropertyGroup>
    <DotNetVersion>10.0.11</DotNetVersion>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <ViciOneClusterBuilderVersion>1.0.0</ViciOneClusterBuilderVersion>
    <ViciOneUiMonochromeIconsVersion>4.16.0</ViciOneUiMonochromeIconsVersion>
  </PropertyGroup>
  <ItemGroup>
    <GlobalPackageReference Include="ViciOne.CodeAnalysis" Version="1.4.0" />
    <PackageVersion Include="AspNetCore.SassCompiler" Version="1.100.0" />
    <PackageVersion Include="AwesomeAssertions" Version="9.6.0" />
    <PackageVersion Include="bunit" Version="2.10.3" />
    <PackageVersion Include="Markdig" Version="0.42.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="$(DotNetVersion)" PrivateAssets="all" />
    <PackageVersion Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.Testing" Version="10.4.0" />
    <PackageVersion Include="Microsoft.Extensions.Localization" Version="$(DotNetVersion)" />
    <PackageVersion Include="Microsoft.Playwright" Version="1.62.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.0" />
    <PackageVersion Include="NSubstitute" Version="6.2.0" />
    <PackageVersion Include="Semver" Version="3.0.0" />
    <PackageVersion Include="StronglyTypedId" Version="0.2.1" />
    <PackageVersion Include="System.IO.Abstractions" Version="22.1.1" />
    <PackageVersion Include="System.Reflection.MetadataLoadContext" Version="$(DotNetVersion)" />
    <PackageVersion Include="ViciOne.Cluster.Model" Version="$(ViciOneClusterBuilderVersion)" />
    <PackageVersion Include="ViciOne.Cluster.Builder" Version="$(ViciOneClusterBuilderVersion)" />
    <PackageVersion Include="ViciOne.Core.Dataflow.DataModel.Generation" Version="1.0.0" />
    <PackageVersion Include="ViciOne.Suite.Core.Artifacts" Version="1.2.2" />
    <PackageVersion Include="ViciOne.Suite.System.DataPort" Version="1.0.0" />
    <PackageVersion Include="ViciOne.Ui.Blazor.Components" Version="5.19.0" />
    <PackageVersion Include="ViciOne.Ui.Design" Version="2.5.0" />
    <PackageVersion Include="ViciOne.Ui.Localization" Version="3.4.0" />
    <PackageVersion Include="ViciOne.Ui.MonochromeIcons.Assets" Version="$(ViciOneUiMonochromeIconsVersion)" />
    <PackageVersion Include="ViciOne.Ui.MonochromeIcons.Components" Version="$(ViciOneUiMonochromeIconsVersion)" />
    <PackageVersion Include="ViciOne.Ui.Shared.Dx" Version="0.19.1" />
    <PackageVersion Include="ViciOne.Ui.Testing.Playwright" Version="1.0.0" />
    <PackageVersion Include="ViciOne.Ui.TreeEditor" Version="2.0.1" />
    <PackageVersion Include="ViciOne.TreeBuilder" Version="2.0.0" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="4.0.0" />
    <PackageVersion Include="Z.Blazor.Diagrams" Version="3.0.4" />
  </ItemGroup>
</Project>
