//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViciOne.Ui.ClusterEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SvgIcons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SvgIcons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViciOne.Ui.ClusterEditor.Resources.SvgIcons", typeof(SvgIcons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 24 24&quot;&gt;&lt;title&gt;arrow-down-right&lt;/title&gt;&lt;path fill=&quot;#DEDEDE&quot; d=&quot;M21.5 14.5L16 20L10.5 14.5L11.91 13.09L15 16.17V10.5C15 8 13 6 10.5 6H4V4H10.5C14.09 4 17 6.91 17 10.5V16.17L20.09 13.08L21.5 14.5Z&quot; /&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string dataflow_structure_block_jump_into {
            get {
                return ResourceManager.GetString("dataflow_structure-block_jump-into", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 24 24&quot;&gt;&lt;title&gt;magnify-expand&lt;/title&gt;&lt;path fill=&quot;#DEDEDE&quot; d=&quot;M18 16H17.42L16.61 15.19C17.5 14 18 12.5 18 11C18 7.13 14.87 4 11 4C9.5 4 8 4.5 6.79 5.4C3.7 7.72 3.07 12.11 5.39 15.2C7.71 18.29 12.1 18.92 15.19 16.6L16 17.41V18L21 23L23 21L18 16M11 16C8.24 16 6 13.76 6 11S8.24 6 11 6 16 8.24 16 11 13.76 16 11 16M3 6L1 8V1H8L6 3H3V6M21 1V8L19 6V3H16L14 1H21M6 19L8 21H1V14L3 16V19H6Z&quot; /&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string dataflow_structure_block_jump_to {
            get {
                return ResourceManager.GetString("dataflow_structure-block_jump-to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 32 32&quot; &gt;
        ///    &lt;g id=&quot;dark/icon/32x32/standard/connector-input&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;
        ///        &lt;path d=&quot;M27,4 L27,28 L13,28 L13,23.2 L15.3333333,23.2 L15.3333333,25.6 L24.6666667,25.6 L24.6666667,6.4 L15.3333333,6.4 L15.3333333,8.8 L13,8.8 L13,4 L27,4 Z M10.9849057,10 L17,15.8990856 L16.898,16 L17,16.1009144 L10.9849057,22 L9.18037737,20.2302743 L12.219,17.251 L3,17.2513858 L3,14.7486157 L12.219,14.748 L9.18037737, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string published_connectors_section_filter_inputs {
            get {
                return ResourceManager.GetString("published-connectors-section_filter-inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 32 32&quot; &gt;
        ///    &lt;g id=&quot;dark/icon/32x32/standard/connector-output&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;
        ///        &lt;path d=&quot;M19,4 L19,8.8 L16.6666667,8.8 L16.6666667,6.4 L7.33333333,6.4 L7.33333333,25.6 L16.6666667,25.6 L16.6666667,23.2 L19,23.2 L19,28 L5,28 L5,4 L19,4 Z M21.9849057,10 L28,15.8990856 L27.898,16 L28,16.1009144 L21.9849057,22 L20.1803774,20.2302743 L23.219,17.251 L14,17.2513858 L14,14.7486157 L23.219,14.748 L20.1803774 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string published_connectors_section_filter_outputs {
            get {
                return ResourceManager.GetString("published-connectors-section_filter-outputs", resourceCulture);
            }
        }
    }
}
