//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViciOne.Ui.ClusterEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SvgIcons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SvgIcons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViciOne.Ui.ClusterEditor.Resources.SvgIcons", typeof(SvgIcons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 24 24&quot;&gt;&lt;title&gt;arrow-down-right&lt;/title&gt;&lt;path fill=&quot;#DEDEDE&quot; d=&quot;M21.5 14.5L16 20L10.5 14.5L11.91 13.09L15 16.17V10.5C15 8 13 6 10.5 6H4V4H10.5C14.09 4 17 6.91 17 10.5V16.17L20.09 13.08L21.5 14.5Z&quot; /&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string dataflow_structure_block_jump_into {
            get {
                return ResourceManager.GetString("dataflow_structure-block_jump-into", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 24 24&quot;&gt;&lt;title&gt;magnify-expand&lt;/title&gt;&lt;path fill=&quot;#DEDEDE&quot; d=&quot;M18 16H17.42L16.61 15.19C17.5 14 18 12.5 18 11C18 7.13 14.87 4 11 4C9.5 4 8 4.5 6.79 5.4C3.7 7.72 3.07 12.11 5.39 15.2C7.71 18.29 12.1 18.92 15.19 16.6L16 17.41V18L21 23L23 21L18 16M11 16C8.24 16 6 13.76 6 11S8.24 6 11 6 16 8.24 16 11 13.76 16 11 16M3 6L1 8V1H8L6 3H3V6M21 1V8L19 6V3H16L14 1H21M6 19L8 21H1V14L3 16V19H6Z&quot; /&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string dataflow_structure_block_jump_to {
            get {
                return ResourceManager.GetString("dataflow_structure-block_jump-to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 32 32&quot; &gt;
        ///    &lt;g id=&quot;dark/icon/32x32/standard/connector-input&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;
        ///        &lt;path d=&quot;M27,4 L27,28 L13,28 L13,23.2 L15.3333333,23.2 L15.3333333,25.6 L24.6666667,25.6 L24.6666667,6.4 L15.3333333,6.4 L15.3333333,8.8 L13,8.8 L13,4 L27,4 Z M10.9849057,10 L17,15.8990856 L16.898,16 L17,16.1009144 L10.9849057,22 L9.18037737,20.2302743 L12.219,17.251 L3,17.2513858 L3,14.7486157 L12.219,14.748 L9.18037737, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string published_connectors_section_filter_inputs {
            get {
                return ResourceManager.GetString("published-connectors-section_filter-inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 32 32&quot; &gt;
        ///    &lt;g id=&quot;dark/icon/32x32/standard/connector-output&quot; stroke=&quot;none&quot; stroke-width=&quot;1&quot; fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;
        ///        &lt;path d=&quot;M19,4 L19,8.8 L16.6666667,8.8 L16.6666667,6.4 L7.33333333,6.4 L7.33333333,25.6 L16.6666667,25.6 L16.6666667,23.2 L19,23.2 L19,28 L5,28 L5,4 L19,4 Z M21.9849057,10 L28,15.8990856 L27.898,16 L28,16.1009144 L21.9849057,22 L20.1803774,20.2302743 L23.219,17.251 L14,17.2513858 L14,14.7486157 L23.219,14.748 L20.1803774 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string published_connectors_section_filter_outputs {
            get {
                return ResourceManager.GetString("published-connectors-section_filter-outputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 32 32&quot;&gt;
        ///  &lt;path d=&quot;M23 7a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H9a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h14Zm0 1H9a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1V9a1 1 0 0 0-1-1Zm-2.513 3 1.346 1.502-4.33 3.915 4.33 3.915-1.346 1.501L16 17.776l-4.487 4.057-1.346-1.501 4.33-3.915-4.33-3.915L11.513 11 16 15.057 20.487 11Z&quot; fill=&quot;#DEDEDE&quot; fill-rule=&quot;evenodd&quot;/&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string searchandtools_section_clear {
            get {
                return ResourceManager.GetString("searchandtools-section_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 32 32&quot;&gt;
        ///  &lt;path fill=&quot;#dedede&quot; fill-rule=&quot;evenodd&quot; d=&quot;m22.955 10.97-5.543 4.573h-.017l.011 8.23-2.797-2.384v-5.837L9.044 10.97V8.227h13.91z&quot;/&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string searchbox_filter {
            get {
                return ResourceManager.GetString("searchbox-filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 32 32&quot;&gt;
        ///  &lt;path fill=&quot;#dedede&quot; fill-rule=&quot;evenodd&quot; d=&quot;M14.364 7a7.333 7.333 0 0 1 7.363 7.364 7.349 7.349 0 0 1-1.573 4.57L25 23.854 23.773 25l-4.802-4.876a7.348 7.348 0 0 1-4.607 1.603A7.333 7.333 0 0 1 7 14.364 7.333 7.333 0 0 1 14.364 7Zm0 1.636a5.692 5.692 0 0 0-5.728 5.728 5.692 5.692 0 0 0 5.728 5.727 5.692 5.692 0 0 0 5.727-5.727 5.692 5.692 0 0 0-5.727-5.728z&quot;/&gt;
        ///&lt;/svg&gt;.
        /// </summary>
        internal static string searchbox_search {
            get {
                return ResourceManager.GetString("searchbox-search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 32 32&quot;&gt;
        ///                            &lt;path d=&quot;M10.615 20 12 21.385 7.154 26.23l2.077 2.077L3 29l.692-6.23 2.077 2.076L10.615 20Zm10.77 0 4.846 4.846 2.077-2.077L29 29l-6.23-.692 2.076-2.077L20 21.385 21.385 20ZM3 3l6.23.692L7.155 5.77 12 10.615 10.615 12 5.77 7.154 3.692 9.23 3 3Zm26 0-.692 6.23-2.077-2.076L21.385 12 20 10.615l4.846-4.846-2.077-2.077L29 3Z&quot; fill=&quot;#FFF&quot; fill-rule=&quot;evenodd&quot; /&gt;
        ///                        &lt;/svg&gt;.
        /// </summary>
        internal static string toolbar_main_fullscreen {
            get {
                return ResourceManager.GetString("toolbar_main-fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 24 24&quot;&gt;&lt;path fill=&quot;currentColor&quot; d=&quot;M21 2H3c-1.1 0-2 .9-2 2v16c0 1.1.9 2 2 2h18c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2m0 5H3V4h18z&quot;/&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string topology_section_application {
            get {
                return ResourceManager.GetString("topology-section_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 24 24&quot;&gt;&lt;path fill=&quot;#FFF&quot; d=&quot;M7 4v2h3v2H7l-2 2v3H3v-3H1v8h2v-3h2v3h3l2 2h8v-4h2v3h3V9h-3v3h-2V8h-6V6h3V4z&quot;/&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string topology_section_engine {
            get {
                return ResourceManager.GetString("topology-section_engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 24 24&quot;&gt;&lt;path fill=&quot;#FFF&quot; d=&quot;M3 15V5a2 2 0 0 1 2-2h6l2 2h6a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-6v2h1a1 1 0 0 1 1 1h7v2h-7a1 1 0 0 1-1 1h-4a1 1 0 0 1-1-1H2v-2h7a1 1 0 0 1 1-1h1v-2H5a2 2 0 0 1-2-2&quot;/&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string topology_section_folder_network {
            get {
                return ResourceManager.GetString("topology-section_folder_network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 24 24&quot;&gt;&lt;path fill=&quot;#FFF&quot; d=&quot;M4 1h16a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1m0 8h16a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-4a1 1 0 0 1 1-1m0 8h16a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-4a1 1 0 0 1 1-1M9 5h1V3H9zm0 8h1v-2H9zm0 8h1v-2H9zM5 3v2h2V3zm0 8v2h2v-2zm0 8v2h2v-2z&quot;/&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string topology_section_server {
            get {
                return ResourceManager.GetString("topology-section_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot; viewBox=&quot;0 0 24 24&quot;&gt;&lt;path fill=&quot;currentColor&quot; d=&quot;M13 19h1a1 1 0 0 1 1 1h7v2h-7a1 1 0 0 1-1 1h-4a1 1 0 0 1-1-1H2v-2h7a1 1 0 0 1 1-1h1v-2H4a1 1 0 0 1-1-1v-4a1 1 0 0 1 1-1h16a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1h-7zM4 3h16a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1m5 4h1V5H9zm0 8h1v-2H9zM5 5v2h2V5zm0 8v2h2v-2z&quot;/&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string topology_section_server_network {
            get {
                return ResourceManager.GetString("topology-section_server_network", resourceCulture);
            }
        }
    }
}
