//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Settings.Components.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsDialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsDialog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Settings.Components.Localization.SettingsDialog", typeof(SettingsDialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid mode.
        /// </summary>
        internal static string GridMode {
            get {
                return ResourceManager.GetString("GridMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string GridModeLine {
            get {
                return ResourceManager.GetString("GridModeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Grid.
        /// </summary>
        internal static string GridModeNone {
            get {
                return ResourceManager.GetString("GridModeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string GridModePoint {
            get {
                return ResourceManager.GetString("GridModePoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node alignment border.
        /// </summary>
        internal static string NodeAlignmentBorderVisible {
            get {
                return ResourceManager.GetString("NodeAlignmentBorderVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show default context menu.
        /// </summary>
        internal static string ShowDefaultContextMenu {
            get {
                return ResourceManager.GetString("ShowDefaultContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimp pan behavior.
        /// </summary>
        internal static string UseGimpPanBehavior {
            get {
                return ResourceManager.GetString("UseGimpPanBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimap coloring.
        /// </summary>
        internal static string UseMinimapColoring {
            get {
                return ResourceManager.GetString("UseMinimapColoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplified view.
        /// </summary>
        internal static string UseSimplifiedView {
            get {
                return ResourceManager.GetString("UseSimplifiedView", resourceCulture);
            }
        }
    }
}
