//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViciOne.Ui.ColorableIcons {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IconParts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IconParts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViciOne.Ui.ColorableIcons.IconParts", typeof(IconParts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg viewBox=&quot;0 0 32 32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;&lt;g fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;path fill=&quot;#F0F&quot; fill-opacity=&quot;.25&quot; d=&quot;M22 8v16h-8v-2h-2V10h2V8h8Z&quot;/&gt;&lt;path fill=&quot;#F0F&quot; d=&quot;M24 6v20H12v-4h2v2h8V8h-8v2h-2V6h12Z&quot;/&gt;&lt;path fill=&quot;#FFF&quot; d=&quot;m16 16-5.16 5-1.54-1.5 2.52-2.45H4v-2.11h7.82L9.3 12.5l1.54-1.5L16 16Z&quot;/&gt;&lt;/g&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string ConnectorInput {
            get {
                return ResourceManager.GetString("ConnectorInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg viewBox=&quot;0 0 32 32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;&lt;g fill=&quot;none&quot; fill-rule=&quot;evenodd&quot;&gt;&lt;path fill=&quot;#F0F&quot; d=&quot;M12 6v20h12v-4h-2v2h-8V8h8v2h2V6H12Z&quot;/&gt;&lt;path fill=&quot;#F0F&quot; fill-opacity=&quot;.25&quot; d=&quot;M22 24h-8V8h8v2h2v12h-2v2Z&quot;/&gt;&lt;path fill=&quot;#FFF&quot; d=&quot;m32 16-5.16 5-1.54-1.5 2.52-2.45H20v-2.11h7.82L25.3 12.5l1.54-1.5L32 16Z&quot;/&gt;&lt;/g&gt;&lt;/svg&gt;.
        /// </summary>
        internal static string ConnectorOutput {
            get {
                return ResourceManager.GetString("ConnectorOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;path d=&quot;M10.5 7.06 7.06 10.5 6.03 9.47l1.74-1.74H2.5V6.27h5.27L6.03 4.53 7.06 3.5l3.44 3.44-.06.06.06.06Z&quot; id=&quot;arrow-in&quot; fill=&quot;#FFF&quot; fill-rule=&quot;evenodd&quot; /&gt;.
        /// </summary>
        internal static string DataPortArrowInPath {
            get {
                return ResourceManager.GetString("DataPortArrowInPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;path d=&quot;m28.5 7.06-3.44 3.44-1.03-1.03 1.74-1.74H20.5V6.27h5.27l-1.74-1.74 1.03-1.03 3.44 3.44-.06.06.06.06Z&quot; id=&quot;arrow-out&quot; fill=&quot;#FFF&quot; fill-rule=&quot;evenodd&quot; /&gt;.
        /// </summary>
        internal static string DataPortArrowOutPath {
            get {
                return ResourceManager.GetString("DataPortArrowOutPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg viewBox=&quot;0 0 32 32&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;{0}&lt;/svg&gt;.
        /// </summary>
        internal static string DataPortIconBody {
            get {
                return ResourceManager.GetString("DataPortIconBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;path d=&quot;M20.51 10.5c.55 0 .99.44.99.99v9.02c0 .55-.44.99-.99.99h-9.02a.99.99 0 0 1-.99-.99v-9.02c0-.55.44-.99.99-.99h9.02Zm-.39 1.38h-8.25v8.24h8.26v-8.25Z&quot; id=&quot;empty&quot; fill=&quot;#F0F&quot; fill-rule=&quot;evenodd&quot; /&gt;.
        /// </summary>
        internal static string DataPortIconEmpty {
            get {
                return ResourceManager.GetString("DataPortIconEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;rect fill=&quot;#F0F&quot; fill-rule=&quot;evenodd&quot; height=&quot;11&quot; id=&quot;filled&quot;  rx=&quot;.96&quot; width=&quot;11&quot; x=&quot;10.5&quot; y=&quot;10.5&quot; /&gt;.
        /// </summary>
        internal static string DataPortIconFilled {
            get {
                return ResourceManager.GetString("DataPortIconFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;path d=&quot;M20.51 10.5c.55 0 .99.44.99.99v9.02c0 .55-.44.99-.99.99h-9.02a.99.99 0 0 1-.99-.99v-9.02c0-.55.44-.99.99-.99h9.02Zm-.39 1.38H16v8.24h4.13v-8.25Z&quot; id=&quot;input-filled&quot; fill=&quot;#F0F&quot; fill-rule=&quot;evenodd&quot; /&gt;.
        /// </summary>
        internal static string DataPortIconInputFilled {
            get {
                return ResourceManager.GetString("DataPortIconInputFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;path d=&quot;M21.5 20.51c0 .55-.44.99-.99.99h-9.02a.99.99 0 0 1-.99-.99v-9.02c0-.55.44-.99.99-.99h9.02c.55 0 .99.44.99.99v9.02ZM16 11.87h-4.13v8.26H16v-8.25Z&quot; id=&quot;output-filled&quot; fill=&quot;#F0F&quot; fill-rule=&quot;evenodd&quot; /&gt;.
        /// </summary>
        internal static string DataPortIconOutputFilled {
            get {
                return ResourceManager.GetString("DataPortIconOutputFilled", resourceCulture);
            }
        }
    }
}
