<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>c50827f6-3148-41fe-9e23-9b0b4aa91c52</UserSecretsId>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPublishable>true</IsPublishable>
    <CompressionEnabled>false</CompressionEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
    <PackageReference Include="ViciOne.Suite.Core.Artifacts" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Client\Client.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
  </ItemGroup>

</Project>
