<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="bunit" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\samples\Server\Server.csproj" />
    <ProjectReference Include="..\..\samples\Shared\Shared.csproj" />
    <ProjectReference Include="..\..\src\ViciOne.Ui.ClusterEditor\ViciOne.Ui.ClusterEditor.csproj" />
    <ProjectReference Include="..\..\src\ViciOne.Ui.ColorableIcons\ViciOne.Ui.ColorableIcons.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\MQTT.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\SQLite.yaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\TestFbDesign.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
