<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <RootNamespace>Shared</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.SassCompiler" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Semver" />
    <PackageReference Include="System.IO.Abstractions" />
    <PackageReference Include="System.Reflection.MetadataLoadContext" />
    <PackageReference Include="ViciOne.Core.Dataflow.DataModel.Generation" />
    <PackageReference Include="ViciOne.Suite.System.DataPort" />
    <PackageReference Include="ViciOne.Ui.Design">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ViciOne.Ui.ClusterEditor\ViciOne.Ui.ClusterEditor.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Localization\Resources\TechnicalTerms.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>TechnicalTerms.resx</DependentUpon>
    </Compile>
    <Compile Update="Persistence\Components\Localization\PersistenceDialog.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PersistenceDialog.resx</DependentUpon>
    </Compile>
    <Compile Update="Settings\Components\Localization\SettingsDialog.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SettingsDialog.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Localization\Resources\TechnicalTerms.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>TechnicalTerms.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Persistence\Components\Localization\PersistenceDialog.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>PersistenceDialog.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Settings\Components\Localization\SettingsDialog.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SettingsDialog.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <!-- Prevent Microsoft.NET.Sdk.Razor from copying unnecessary file -->
  <ItemGroup>
    <Content Update="sasscompiler.json" CopyToOutputDirectory="Never" CopyToPublishDirectory="Never" Pack="False" />
  </ItemGroup>

  <Target Name="ConfigureDesignTargets" BeforeTargets="BeforeDesignTargets">
    <PropertyGroup>
      <ColorsScssOutputFolder>$(MSBuildProjectDirectory)/Styles/design/colors</ColorsScssOutputFolder>
    </PropertyGroup>
  </Target>
</Project>
