//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViciOne.Ui.ClusterEditor.Sections.DataPorts.Components.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataPortSection {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataPortSection() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViciOne.Ui.ClusterEditor.Sections.DataPorts.Components.Localization.DataPortSecti" +
                            "on", typeof(DataPortSection).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the node along with it&apos;s child nodes?.
        /// </summary>
        internal static string ConfirmDeleteNode {
            get {
                return ResourceManager.GetString("ConfirmDeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added a new element while a filter is active. (total {0}).
        /// </summary>
        internal static string ElementAddedWhileFilteredInfo {
            get {
                return ResourceManager.GetString("ElementAddedWhileFilteredInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new child.
        /// </summary>
        internal static string NewChild {
            get {
                return ResourceManager.GetString("NewChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new DataPort.
        /// </summary>
        internal static string NewDataPort {
            get {
                return ResourceManager.GetString("NewDataPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0}.
        /// </summary>
        internal static string NodeActionAdd {
            get {
                return ResourceManager.GetString("NodeActionAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort children.
        /// </summary>
        internal static string NodeActionSortChildren {
            get {
                return ResourceManager.GetString("NodeActionSortChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently the ValueType is disabled. This can happen if the data port element only supports one value type or if one or more connectors are linked to the dataport element and there are no other compatible value types..
        /// </summary>
        internal static string ValueTypeDisabledInformation {
            get {
                return ResourceManager.GetString("ValueTypeDisabledInformation", resourceCulture);
            }
        }
    }
}
