//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViciOne.Ui.ClusterEditor.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TechnicalTerms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TechnicalTerms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViciOne.Ui.ClusterEditor.Localization.Resources.TechnicalTerms", typeof(TechnicalTerms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        internal static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks.
        /// </summary>
        internal static string BlockPlural {
            get {
                return ResourceManager.GetString("BlockPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cluster.
        /// </summary>
        internal static string Cluster {
            get {
                return ResourceManager.GetString("Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector.
        /// </summary>
        internal static string Connector {
            get {
                return ResourceManager.GetString("Connector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectors.
        /// </summary>
        internal static string ConnectorPlural {
            get {
                return ResourceManager.GetString("ConnectorPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        internal static string Container {
            get {
                return ResourceManager.GetString("Container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containers.
        /// </summary>
        internal static string ContainerPlural {
            get {
                return ResourceManager.GetString("ContainerPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dataflow.
        /// </summary>
        internal static string Dataflow {
            get {
                return ResourceManager.GetString("Dataflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataPort.
        /// </summary>
        internal static string DataPort {
            get {
                return ResourceManager.GetString("DataPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataPorts.
        /// </summary>
        internal static string DataPortPlural {
            get {
                return ResourceManager.GetString("DataPortPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataPort TreeNodes.
        /// </summary>
        internal static string DataPortTreeNodePlural {
            get {
                return ResourceManager.GetString("DataPortTreeNodePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value.
        /// </summary>
        internal static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers.
        /// </summary>
        internal static string DriverPlural {
            get {
                return ResourceManager.GetString("DriverPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine.
        /// </summary>
        internal static string Engine {
            get {
                return ResourceManager.GetString("Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engines.
        /// </summary>
        internal static string EnginePlural {
            get {
                return ResourceManager.GetString("EnginePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventEnabled.
        /// </summary>
        internal static string EventEnabled {
            get {
                return ResourceManager.GetString("EventEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FunctionBlock.
        /// </summary>
        internal static string FunctionBlock {
            get {
                return ResourceManager.GetString("FunctionBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FunctionBlock Designs.
        /// </summary>
        internal static string FunctionBlockDesignPlural {
            get {
                return ResourceManager.GetString("FunctionBlockDesignPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FunctionBlocks.
        /// </summary>
        internal static string FunctionBlockPlural {
            get {
                return ResourceManager.GetString("FunctionBlockPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to including system connectors.
        /// </summary>
        internal static string IncludingSystemConnectors {
            get {
                return ResourceManager.GetString("IncludingSystemConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Connectors.
        /// </summary>
        internal static string InputConnectorPlural {
            get {
                return ResourceManager.GetString("InputConnectorPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        internal static string LinkPlural {
            get {
                return ResourceManager.GetString("LinkPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loggers.
        /// </summary>
        internal static string LoggerPlural {
            get {
                return ResourceManager.GetString("LoggerPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        internal static string Namespace {
            get {
                return ResourceManager.GetString("Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        internal static string Node {
            get {
                return ResourceManager.GetString("Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Connectors.
        /// </summary>
        internal static string OutputConnectorPlural {
            get {
                return ResourceManager.GetString("OutputConnectorPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pooling.
        /// </summary>
        internal static string Pooling {
            get {
                return ResourceManager.GetString("Pooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PoolingStrategy.
        /// </summary>
        internal static string PoolingStrategy {
            get {
                return ResourceManager.GetString("PoolingStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predecessor.
        /// </summary>
        internal static string Predecessor {
            get {
                return ResourceManager.GetString("Predecessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predecessors.
        /// </summary>
        internal static string PredecessorPlural {
            get {
                return ResourceManager.GetString("PredecessorPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Mode Settings.
        /// </summary>
        internal static string RunModeSettingPlural {
            get {
                return ResourceManager.GetString("RunModeSettingPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successor.
        /// </summary>
        internal static string Successor {
            get {
                return ResourceManager.GetString("Successor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successors.
        /// </summary>
        internal static string SuccessorPlural {
            get {
                return ResourceManager.GetString("SuccessorPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        internal static string TemplatePlural {
            get {
                return ResourceManager.GetString("TemplatePlural", resourceCulture);
            }
        }
    }
}
