//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViciOne.Ui.ClusterEditor.Components.ContextMenu.Specialized.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NodeEditorContextMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NodeEditorContextMenu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViciOne.Ui.ClusterEditor.Components.ContextMenu.Specialized.Localization.NodeEdit" +
                            "orContextMenu", typeof(NodeEditorContextMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add container.
        /// </summary>
        internal static string AddContainer {
            get {
                return ResourceManager.GetString("AddContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add label.
        /// </summary>
        internal static string AddLabel {
            get {
                return ResourceManager.GetString("AddLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring to front.
        /// </summary>
        internal static string BringToFront {
            get {
                return ResourceManager.GetString("BringToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissolve container.
        /// </summary>
        internal static string DissolveContainer {
            get {
                return ResourceManager.GetString("DissolveContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine assignment.
        /// </summary>
        internal static string EngineAssignment {
            get {
                return ResourceManager.GetString("EngineAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock labels.
        /// </summary>
        internal static string LockLabels {
            get {
                return ResourceManager.GetString("LockLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to new container.
        /// </summary>
        internal static string MoveToNewContainer {
            get {
                return ResourceManager.GetString("MoveToNewContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all blocks.
        /// </summary>
        internal static string SelectAllBlocks {
            get {
                return ResourceManager.GetString("SelectAllBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectors Wizard.
        /// </summary>
        internal static string SelectConnectorsWizard {
            get {
                return ResourceManager.GetString("SelectConnectorsWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select input &amp; output connectors.
        /// </summary>
        internal static string SelectInputAndOutputConnectors {
            get {
                return ResourceManager.GetString("SelectInputAndOutputConnectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to back.
        /// </summary>
        internal static string SendToBack {
            get {
                return ResourceManager.GetString("SendToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassign engine.
        /// </summary>
        internal static string UnassignEngine {
            get {
                return ResourceManager.GetString("UnassignEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock labels.
        /// </summary>
        internal static string UnlockLabels {
            get {
                return ResourceManager.GetString("UnlockLabels", resourceCulture);
            }
        }
    }
}
