//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViciOne.Ui.ClusterEditor.Helpers.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TooltipData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TooltipData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViciOne.Ui.ClusterEditor.Helpers.Localization.TooltipData", typeof(TooltipData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned engine.
        /// </summary>
        internal static string AssignedEngine {
            get {
                return ResourceManager.GetString("AssignedEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belongs to driver.
        /// </summary>
        internal static string BelongsToDriver {
            get {
                return ResourceManager.GetString("BelongsToDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current CycleFrequency.
        /// </summary>
        internal static string CurrentCycleFrequency {
            get {
                return ResourceManager.GetString("CurrentCycleFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current RunMode.
        /// </summary>
        internal static string CurrentRunMode {
            get {
                return ResourceManager.GetString("CurrentRunMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle time maximum.
        /// </summary>
        internal static string CycleTimeMax {
            get {
                return ResourceManager.GetString("CycleTimeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle time minimum.
        /// </summary>
        internal static string CycleTimeMin {
            get {
                return ResourceManager.GetString("CycleTimeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default CycleFrequency.
        /// </summary>
        internal static string DefaultCycleFrequency {
            get {
                return ResourceManager.GetString("DefaultCycleFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default RunMode.
        /// </summary>
        internal static string DefaultRunMode {
            get {
                return ResourceManager.GetString("DefaultRunMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains unassigned FunctionBlocks.
        /// </summary>
        internal static string EngineContainsUnassigned {
            get {
                return ResourceManager.GetString("EngineContainsUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link count.
        /// </summary>
        internal static string LinkCount {
            get {
                return ResourceManager.GetString("LinkCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And ({0}) more....
        /// </summary>
        internal static string MoreLinks {
            get {
                return ResourceManager.GetString("MoreLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Receive.
        /// </summary>
        internal static string ToReceive {
            get {
                return ResourceManager.GetString("ToReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Send.
        /// </summary>
        internal static string ToSend {
            get {
                return ResourceManager.GetString("ToSend", resourceCulture);
            }
        }
    }
}
