//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViciOne.Ui.ClusterEditor.Sections.Dataflow.Services.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataflowStructureTreeAdapter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataflowStructureTreeAdapter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViciOne.Ui.ClusterEditor.Sections.Dataflow.Services.Localization.DataflowStructur" +
                            "eTreeAdapter", typeof(DataflowStructureTreeAdapter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Dataflow.
        /// </summary>
        internal static string AddDataflow {
            get {
                return ResourceManager.GetString("AddDataflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete the Dataflow &apos;{0}&apos;?.
        /// </summary>
        internal static string ConfirmDeleteDataflow {
            get {
                return ResourceManager.GetString("ConfirmDeleteDataflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Dataflow while a filter is active. (total {0}).
        /// </summary>
        internal static string DataflowAddedWhileFilteredInfo {
            get {
                return ResourceManager.GetString("DataflowAddedWhileFilteredInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Dataflow.
        /// </summary>
        internal static string DeleteDataflowHeader {
            get {
                return ResourceManager.GetString("DeleteDataflowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to Container.
        /// </summary>
        internal static string JumpToContainer {
            get {
                return ResourceManager.GetString("JumpToContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to FunctionBlock.
        /// </summary>
        internal static string JumpToFunctionBlock {
            get {
                return ResourceManager.GetString("JumpToFunctionBlock", resourceCulture);
            }
        }
    }
}
